### PR TITLE
Horizontal mouse wheel scrolling

### PR DESCRIPTION
**Pull request by daniel-sanche**
Previously, there was one method for the scroll wheel, which would scroll both vertically and horizontally at the same time. This PR breaks it up into tow separate functions: `on_mouse_wheel` for vertical scrolling, and `on_mouse_wheel_horizontal` for horizontal scrolling

### CODE REVIEW

**Comment by Lecrapouille** [comment]
@daniel-sanche yes, I'll add the `_vertical` int the name and deprecate the old name. By the way, are you a MacOS dev ?

**Comment by daniel-sanche** [comment]
Not typically, but I've done some iOS and macOS work in the past. Why?

**Comment by Lecrapouille** [comment]
@daniel-sanche just to know if you want to make a portage of CEF for macOS (beware: 5-stars difficulty)

**Comment by daniel-sanche** [comment]
Yeah that's probably a bit out of my depth for now, but I might try to take a look at it at some point! Was it ever working for macOS? I saw a bunch of comments around it in the build script

**Comment by Lecrapouille** [comment]
I could end compiling, but I know there is missing functional code. I asked https://github.com/CefView/CefViewCore, but not sure to achieve it, but for now that is fine!

**Pull request merged**
