### PR TITLE
Documentation correction/simplification

### PR DESCRIPTION
**Pull request by raphipod**
This pull request is only dedicated to correcting language mistakes and simplyfing the README file & maybe some docs

The README file correcting is done as is, now I will search for other things to be corrected especially in the /doc folder.

**Note: I won't add any content to any of those files, it's just some corrections. I don't quite know yet how this project works underneath, but maybe I'll give it a shot in the next PR's.**

### CODE REVIEW

**Comment by Lecrapouille** [comment]
@raphipod thank you ! My English is poor :) and the detail design is unfinished because I left before ended writing it.

**Comment by raphipod** [comment]
Ah, ok. No worries.

**Comment by raphipod** [comment]
Allright. I think I've done everything I wanted to do. [PR 0af0435 ](https://github.com/Lecrapouille/gdcef/pull/4/commits/0af04352b9130499a029af8b4a149ef27fa3f884) just updated the CEF version, while I was at it.

Ready to commit.

**Comment by raphipod** [comment]
Now that Godot 3.5 is out, should we migrate gdcef to it?

**Comment by Lecrapouille** [comment]
@raphipod Yes we can try to switch to Godot 3.5 by changing this line:
https://github.com/Lecrapouille/gdcef/blob/1a2a27a961325bae7bee48fd854743104301f827/build.py#L324
But I will not be able to test until end of August

**Pull request merged**
